services:
  ch-ui:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        PROXY: ${HTTP_PROXY:-http://172.21.10.22:8888/}
    restart: always
    ports:
      - "${CH_UI_PORT:-5521}:5521"
    environment:
      VITE_CLICKHOUSE_URL: "${CLICKHOUSE_URL}"
      VITE_CLICKHOUSE_USER: "${CLICKHOUSE_USER}"
      VITE_CLICKHOUSE_PASS: "${CLICKHOUSE_PASS}"

